on:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ci

    env:
      DOCKER_HOST: tcp://docker-in-docker:2375
      IMAGE: codeberg.org/${{ forgejo.repository_owner }}/kabai-ui

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Codeberg Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login codeberg.org \
            --username "${{ forgejo.repository_owner }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build \
            --tag "$IMAGE:latest" \
            --tag "$IMAGE:${{ forgejo.ref_name }}" \
            .

      - name: Push Docker image
        run: |
          docker push "$IMAGE:latest"
          docker push "$IMAGE:${{ forgejo.ref_name }}"
