on:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ci

    env:
      DOCKER_HOST: tcp://docker-in-docker:2375

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Codeberg Registry
        uses: docker/login-action@v3
        with:
          registry: codeberg.org/${{ forgejo.repository_owner }}
          username: ${{ forgejo.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            codeberg.org/${{ forgejo.repository_owner }}/kabai-ui:latest
            codeberg.org/${{ forgejo.repository_owner }}/kabai-ui:${{ forgejo.ref_name }}
